version: '3.7'

services:
  mongo:
    image: mongo:4.2
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

  mongo-express:
    image: mongo-express:0.54
    ports:
      - 8081:8081
    # environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: root

volumes:
  data:
